//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Didache.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class emails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal emails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Didache.Resources.emails", typeof(emails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {touser-secureshortname},
        ///
        ///{fromuser-secureshortname} has requested to be your &apos;Friend&apos; (or &apos;Classmate&apos;).
        ///
        ///You can approve the request at https://online.dts.edu/community/friend/. 
        ///
        ///If you approve the request, you and {fromuser-secureshortname} will be able keep track of one another more easily, and you will also be able to control who in the DTS network can view your profile information by going to http://online.dts.edu/account/editprofile/
        ///
        ///Thanks!
        ///
        ///DTS Online
        ///https://online.dts.edu/.
        /// </summary>
        public static string classmates_approvalrequest {
            get {
                return ResourceManager.GetString("classmates_approvalrequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {touser-secureshortname},
        ///
        ///{fromuser-secureformattedname} has invited you to join the group &apos;{discussiongroup-name}.&apos; If you&apos;d like to join, please visit {discussiongroup-groupurl} and click the &quot;Accept Invite&quot; button. This will allow you to share updates, give advice, or ask questions to those with similar interests.
        ///
        ///DTS Online
        ///https://online.dts.edu/.
        /// </summary>
        public static string discussiongroup_invitation {
            get {
                return ResourceManager.GetString("discussiongroup_invitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {touser-secureshortname},
        ///
        ///{fromuser-secureshortname} has posted a new message to &apos;{discussiongroup-name}&apos; a group to which you have subscribed.
        ///
        ///--------------------------------
        ///{userpost-text}
        ///--------------------------------
        ///
        ///Read more here: 
        ///{userpost-posturl}
        ///
        ///DTS Online
        ///https://online.dts.edu/.
        /// </summary>
        public static string discussiongroup_message {
            get {
                return ResourceManager.GetString("discussiongroup_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assignment {task-name} in {course-code} has been graded by {fromuser-secureformattedname}. 
        ///
        ///Grade: {usertaskdata-numericgrade}
        ///Graded File: {usertaskdata-gradedfile-url}
        ///Grader Comments: 
        ///{usertaskdata-gradercomments}
        ///
        ///Your File: {usertaskdata-studentfile-url}
        ///Your Comments:
        ///{usertaskdata-studentcomments}.
        /// </summary>
        public static string gradedtask_body {
            get {
                return ResourceManager.GetString("gradedtask_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you uploaded for the assignment {task-name} in {course-code} has been removed by {fromuser-secureformattedname} so that you can upload a new one..
        /// </summary>
        public static string gradedtask_removed {
            get {
                return ResourceManager.GetString("gradedtask_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {course-code} - {task-name} graded.
        /// </summary>
        public static string gradedtask_subject {
            get {
                return ResourceManager.GetString("gradedtask_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {touser-secureshortname},
        ///
        ///{fromuser-secureshortname} added a reply to a thread in which you have participated at https://online.dts.edu/
        ///
        ///--------------------------------
        ///{interactionpost-postcontent}
        ///--------------------------------
        ///
        ///See the complete thread here:
        ///{interactionpost-posturl}
        ///
        ///Please note: you can control the notifications you receive at https://online.dts.edu/account/editprofile
        ///
        ///DTS Online
        ///https://online.dts.edu/.
        /// </summary>
        public static string interaction_reply {
            get {
                return ResourceManager.GetString("interaction_reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {touser-secureshortname},
        ///
        ///{fromuser-secureshortname} has made an announcement on DTS Online.
        ///
        ///--------------------------------
        ///{userpost-text}
        ///--------------------------------
        ///
        ///Read more here: 
        ///{userpost-posturl}
        ///
        ///DTS Online
        ///https://online.dts.edu/.
        /// </summary>
        public static string userpost_announcement {
            get {
                return ResourceManager.GetString("userpost_announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {touser-secureshortname},
        ///
        ///{fromuser-secureshortname} added a comment to one of your posts at DTS Online.
        ///
        ///--------------------------------
        ///{postcomment-text}
        ///--------------------------------
        ///
        ///Read more here: 
        ///{userpost-posturl}
        ///
        ///Please note: you can control the notifications you receive at https://online.dts.edu/account/editprofile
        ///
        ///DTS Online
        ///https://online.dts.edu/.
        /// </summary>
        public static string userpost_comment {
            get {
                return ResourceManager.GetString("userpost_comment", resourceCulture);
            }
        }
    }
}
