//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Didache.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Didache.Resources.labels", typeof(labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alumni.
        /// </summary>
        public static string commonmenu_alumni {
            get {
                return ResourceManager.GetString("commonmenu_alumni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Center.
        /// </summary>
        public static string commonmenu_bookcenter {
            get {
                return ResourceManager.GetString("commonmenu_bookcenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CampusNet.
        /// </summary>
        public static string commonmenu_campusnet {
            get {
                return ResourceManager.GetString("commonmenu_campusnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTS Website.
        /// </summary>
        public static string commonmenu_dtswebsite {
            get {
                return ResourceManager.GetString("commonmenu_dtswebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string commonmenu_library {
            get {
                return ResourceManager.GetString("commonmenu_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Ed.
        /// </summary>
        public static string commonmenu_onlineed {
            get {
                return ResourceManager.GetString("commonmenu_onlineed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        public static string confirm_delete {
            get {
                return ResourceManager.GetString("confirm_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Courses.
        /// </summary>
        public static string coursemenu_active_courses {
            get {
                return ResourceManager.GetString("coursemenu_active_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived Courses.
        /// </summary>
        public static string coursemenu_archived_courses {
            get {
                return ResourceManager.GetString("coursemenu_archived_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string coursemenu_calendar {
            get {
                return ResourceManager.GetString("coursemenu_calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string coursemenu_other_courses {
            get {
                return ResourceManager.GetString("coursemenu_other_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived Courses.
        /// </summary>
        public static string courses_heading_archivedcourses {
            get {
                return ResourceManager.GetString("courses_heading_archivedcourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments.
        /// </summary>
        public static string courses_heading_assignments {
            get {
                return ResourceManager.GetString("courses_heading_assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Description.
        /// </summary>
        public static string courses_heading_coursedesc {
            get {
                return ResourceManager.GetString("courses_heading_coursedesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Files.
        /// </summary>
        public static string courses_heading_coursefiles {
            get {
                return ResourceManager.GetString("courses_heading_coursefiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Roster.
        /// </summary>
        public static string courses_heading_courseroster {
            get {
                return ResourceManager.GetString("courses_heading_courseroster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming....
        /// </summary>
        public static string courses_heading_dashboard {
            get {
                return ResourceManager.GetString("courses_heading_dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string courses_heading_tools {
            get {
                return ResourceManager.GetString("courses_heading_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string courses_heading_units {
            get {
                return ResourceManager.GetString("courses_heading_units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graded Files.
        /// </summary>
        public static string courses_label_gradedfiles {
            get {
                return ResourceManager.GetString("courses_label_gradedfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Feed.
        /// </summary>
        public static string courses_tools_icalendar {
            get {
                return ResourceManager.GetString("courses_tools_icalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the links below to import course requirements into your calendar program (Mac Mail, Outlook, Google Calendar, etc.).
        /// </summary>
        public static string courses_tools_icalendar_desc {
            get {
                return ResourceManager.GetString("courses_tools_icalendar_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTunes Feed.
        /// </summary>
        public static string courses_tools_itunes {
            get {
                return ResourceManager.GetString("courses_tools_itunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import course videos, slides, and transcripts into iTunes (or other media software) for offline viewing..
        /// </summary>
        public static string courses_tools_itunes_desc {
            get {
                return ResourceManager.GetString("courses_tools_itunes_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments.
        /// </summary>
        public static string coursetabs_assignments {
            get {
                return ResourceManager.GetString("coursetabs_assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get your graded stuff.
        /// </summary>
        public static string coursetabs_assignments_desc {
            get {
                return ResourceManager.GetString("coursetabs_assignments_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string coursetabs_dashboard {
            get {
                return ResourceManager.GetString("coursetabs_dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All your base.
        /// </summary>
        public static string coursetabs_dashboard_desc {
            get {
                return ResourceManager.GetString("coursetabs_dashboard_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the important information about your class.
        /// </summary>
        public static string coursetabs_dashboard_desc_long {
            get {
                return ResourceManager.GetString("coursetabs_dashboard_desc_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discussion.
        /// </summary>
        public static string coursetabs_discussion {
            get {
                return ResourceManager.GetString("coursetabs_discussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Forums.
        /// </summary>
        public static string coursetabs_discussion_desc {
            get {
                return ResourceManager.GetString("coursetabs_discussion_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string coursetabs_files {
            get {
                return ResourceManager.GetString("coursetabs_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prof&apos;s materials.
        /// </summary>
        public static string coursetabs_files_desc {
            get {
                return ResourceManager.GetString("coursetabs_files_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roster.
        /// </summary>
        public static string coursetabs_roster {
            get {
                return ResourceManager.GetString("coursetabs_roster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet your classmates.
        /// </summary>
        public static string coursetabs_roster_desc {
            get {
                return ResourceManager.GetString("coursetabs_roster_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string coursetabs_schedule {
            get {
                return ResourceManager.GetString("coursetabs_schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dates &amp;amp; assignments.
        /// </summary>
        public static string coursetabs_schedule_desc {
            get {
                return ResourceManager.GetString("coursetabs_schedule_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string coursetabs_tools {
            get {
                return ResourceManager.GetString("coursetabs_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads, Calendars, and RSS feeds.
        /// </summary>
        public static string coursetabs_tools_desc {
            get {
                return ResourceManager.GetString("coursetabs_tools_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while processing your request.
        /// </summary>
        public static string error_desc {
            get {
                return ResourceManager.GetString("error_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string forums_by {
            get {
                return ResourceManager.GetString("forums_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Forums.
        /// </summary>
        public static string forums_courseforums {
            get {
                return ResourceManager.GetString("forums_courseforums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum Name.
        /// </summary>
        public static string forums_header_forumname {
            get {
                return ResourceManager.GetString("forums_header_forumname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Post.
        /// </summary>
        public static string forums_header_lastpost {
            get {
                return ResourceManager.GetString("forums_header_lastpost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string forums_header_threadsubject {
            get {
                return ResourceManager.GetString("forums_header_threadsubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string forums_header_totalposts {
            get {
                return ResourceManager.GetString("forums_header_totalposts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replies.
        /// </summary>
        public static string forums_header_totalreplies {
            get {
                return ResourceManager.GetString("forums_header_totalreplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threads.
        /// </summary>
        public static string forums_header_totalthreads {
            get {
                return ResourceManager.GetString("forums_header_totalthreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string forums_header_totalviews {
            get {
                return ResourceManager.GetString("forums_header_totalviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string forums_replytopost {
            get {
                return ResourceManager.GetString("forums_replytopost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email.
        /// </summary>
        public static string help_email {
            get {
                return ResourceManager.GetString("help_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;re having a login problem, please use the &lt;a href=&quot;http://www.dts.edu/account/resetpassword&quot;&gt;reset password&lt;/a&gt; link to reset your password. If you have a question about an assignment, please contact your professor or facilitator..
        /// </summary>
        public static string help_instructions {
            get {
                return ResourceManager.GetString("help_instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of Problem.
        /// </summary>
        public static string help_message {
            get {
                return ResourceManager.GetString("help_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string help_name {
            get {
                return ResourceManager.GetString("help_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Problem.
        /// </summary>
        public static string help_submit {
            get {
                return ResourceManager.GetString("help_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your feedback. Someone will response as soon as possible..
        /// </summary>
        public static string help_submitted {
            get {
                return ResourceManager.GetString("help_submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help/Contact.
        /// </summary>
        public static string help_title {
            get {
                return ResourceManager.GetString("help_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Courses.
        /// </summary>
        public static string home_currentcourses {
            get {
                return ResourceManager.GetString("home_currentcourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bibliography Software.
        /// </summary>
        public static string home_dashboard_heading_bibsoftware {
            get {
                return ResourceManager.GetString("home_dashboard_heading_bibsoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Resources.
        /// </summary>
        public static string home_dashboard_heading_courseresources {
            get {
                return ResourceManager.GetString("home_dashboard_heading_courseresources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Education Resources.
        /// </summary>
        public static string home_dashboard_heading_onlineedresources {
            get {
                return ResourceManager.GetString("home_dashboard_heading_onlineedresources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s Happening on MyDTS.
        /// </summary>
        public static string home_dashboard_heading_stream {
            get {
                return ResourceManager.GetString("home_dashboard_heading_stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming.
        /// </summary>
        public static string home_dashboard_heading_upcoming {
            get {
                return ResourceManager.GetString("home_dashboard_heading_upcoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download all files (current courses).
        /// </summary>
        public static string home_dashboard_li_downloadallfiles {
            get {
                return ResourceManager.GetString("home_dashboard_li_downloadallfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download your term calendar.
        /// </summary>
        public static string home_dashboard_li_downloadcalendar {
            get {
                return ResourceManager.GetString("home_dashboard_li_downloadcalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndNote.
        /// </summary>
        public static string home_dashboard_li_endnote {
            get {
                return ResourceManager.GetString("home_dashboard_li_endnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LibreOffice.org.
        /// </summary>
        public static string home_dashboard_li_libreoffice {
            get {
                return ResourceManager.GetString("home_dashboard_li_libreoffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Word Compatibility Pack.
        /// </summary>
        public static string home_dashboard_li_msword {
            get {
                return ResourceManager.GetString("home_dashboard_li_msword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleEase.
        /// </summary>
        public static string home_dashboard_li_styleease {
            get {
                return ResourceManager.GetString("home_dashboard_li_styleease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turabian Format Tutorial.
        /// </summary>
        public static string home_dashboard_li_turabianformattutorial {
            get {
                return ResourceManager.GetString("home_dashboard_li_turabianformattutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zotero (free).
        /// </summary>
        public static string home_dashboard_li_zotero {
            get {
                return ResourceManager.GetString("home_dashboard_li_zotero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any currently active courses.
        /// </summary>
        public static string home_nocourses {
            get {
                return ResourceManager.GetString("home_nocourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the home page where all your stuff should be.
        /// </summary>
        public static string homemenu_message {
            get {
                return ResourceManager.GetString("homemenu_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Page.
        /// </summary>
        public static string index_title {
            get {
                return ResourceManager.GetString("index_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open [{0} Replies].
        /// </summary>
        public static string interactions_replies {
            get {
                return ResourceManager.GetString("interactions_replies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download All Files.
        /// </summary>
        public static string labels_dashboard_downloadallfiles {
            get {
                return ResourceManager.GetString("labels_dashboard_downloadallfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faciliators.
        /// </summary>
        public static string labels_dashboard_facilitators {
            get {
                return ResourceManager.GetString("labels_dashboard_facilitators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty.
        /// </summary>
        public static string labels_dashboard_faculty {
            get {
                return ResourceManager.GetString("labels_dashboard_faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Members.
        /// </summary>
        public static string labels_dashboard_groupmembers {
            get {
                return ResourceManager.GetString("labels_dashboard_groupmembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Assignments.
        /// </summary>
        public static string labels_dashboard_keyassignments {
            get {
                return ResourceManager.GetString("labels_dashboard_keyassignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string labels_dashboard_keydownloads {
            get {
                return ResourceManager.GetString("labels_dashboard_keydownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syllabus.
        /// </summary>
        public static string labels_dashboard_syllabus {
            get {
                return ResourceManager.GetString("labels_dashboard_syllabus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot ID/Password.
        /// </summary>
        public static string login_forgotpassword {
            get {
                return ResourceManager.GetString("login_forgotpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username and password.
        /// </summary>
        public static string login_instructions {
            get {
                return ResourceManager.GetString("login_instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string login_legend {
            get {
                return ResourceManager.GetString("login_legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login_login {
            get {
                return ResourceManager.GetString("login_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string login_logout {
            get {
                return ResourceManager.GetString("login_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string login_password {
            get {
                return ResourceManager.GetString("login_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep me logged in.
        /// </summary>
        public static string login_rememberme {
            get {
                return ResourceManager.GetString("login_rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login_title {
            get {
                return ResourceManager.GetString("login_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string login_unsuccessful {
            get {
                return ResourceManager.GetString("login_unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTS ID or Email.
        /// </summary>
        public static string login_username {
            get {
                return ResourceManager.GetString("login_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alumni.
        /// </summary>
        public static string profile_constituency_alumni {
            get {
                return ResourceManager.GetString("profile_constituency_alumni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty.
        /// </summary>
        public static string profile_constituency_faculty {
            get {
                return ResourceManager.GetString("profile_constituency_faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string profile_constituency_staff {
            get {
                return ResourceManager.GetString("profile_constituency_staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string profile_constituency_student {
            get {
                return ResourceManager.GetString("profile_constituency_student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string profile_edit_button {
            get {
                return ResourceManager.GetString("profile_edit_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string profile_heading_contactinfo {
            get {
                return ResourceManager.GetString("profile_heading_contactinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string profile_heading_personalinfo {
            get {
                return ResourceManager.GetString("profile_heading_personalinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string profile_heading_preferences {
            get {
                return ResourceManager.GetString("profile_heading_preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media.
        /// </summary>
        public static string profile_heading_socialmedia {
            get {
                return ResourceManager.GetString("profile_heading_socialmedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string profile_label_address {
            get {
                return ResourceManager.GetString("profile_label_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biography.
        /// </summary>
        public static string profile_label_biography {
            get {
                return ResourceManager.GetString("profile_label_biography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        public static string profile_label_birthday {
            get {
                return ResourceManager.GetString("profile_label_birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string profile_label_email {
            get {
                return ResourceManager.GetString("profile_label_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hometown.
        /// </summary>
        public static string profile_label_hometown {
            get {
                return ResourceManager.GetString("profile_label_hometown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string profile_label_language {
            get {
                return ResourceManager.GetString("profile_label_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string profile_label_phone {
            get {
                return ResourceManager.GetString("profile_label_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone.
        /// </summary>
        public static string profile_label_timezone {
            get {
                return ResourceManager.GetString("profile_label_timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Profile.
        /// </summary>
        public static string profile_save_button {
            get {
                return ResourceManager.GetString("profile_save_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All DTS.
        /// </summary>
        public static string profile_security_all {
            get {
                return ResourceManager.GetString("profile_security_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classmates.
        /// </summary>
        public static string profile_security_friends {
            get {
                return ResourceManager.GetString("profile_security_friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string profile_security_private {
            get {
                return ResourceManager.GetString("profile_security_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string studentschedule_choose {
            get {
                return ResourceManager.GetString("studentschedule_choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please submit one of the following file types:.
        /// </summary>
        public static string studentschedule_chooseafiletype {
            get {
                return ResourceManager.GetString("studentschedule_chooseafiletype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string studentschedule_file {
            get {
                return ResourceManager.GetString("studentschedule_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The instructions for this assignment will be available {0}..
        /// </summary>
        public static string studentschedule_instructionsnotavailable {
            get {
                return ResourceManager.GetString("studentschedule_instructionsnotavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Completed.
        /// </summary>
        public static string studentschedule_markcompleted {
            get {
                return ResourceManager.GetString("studentschedule_markcompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string studentschedule_skip {
            get {
                return ResourceManager.GetString("studentschedule_skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be able to submit this assignment begining {0}..
        /// </summary>
        public static string studentschedule_submissionnotavailable {
            get {
                return ResourceManager.GetString("studentschedule_submissionnotavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn in File.
        /// </summary>
        public static string studentschedule_submitfile {
            get {
                return ResourceManager.GetString("studentschedule_submitfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Assignment for Discussion.
        /// </summary>
        public static string studentschedule_submitfordiscussion {
            get {
                return ResourceManager.GetString("studentschedule_submitfordiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string submenu_archive {
            get {
                return ResourceManager.GetString("submenu_archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campuses.
        /// </summary>
        public static string submenu_campuses {
            get {
                return ResourceManager.GetString("submenu_campuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classmates.
        /// </summary>
        public static string submenu_community_home {
            get {
                return ResourceManager.GetString("submenu_community_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string submenu_courses {
            get {
                return ResourceManager.GetString("submenu_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string submenu_current {
            get {
                return ResourceManager.GetString("submenu_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string submenu_dashboard {
            get {
                return ResourceManager.GetString("submenu_dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string submenu_edit {
            get {
                return ResourceManager.GetString("submenu_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string submenu_files {
            get {
                return ResourceManager.GetString("submenu_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        public static string submenu_sessions {
            get {
                return ResourceManager.GetString("submenu_sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string submenu_tools {
            get {
                return ResourceManager.GetString("submenu_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string submenu_users {
            get {
                return ResourceManager.GetString("submenu_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile Page.
        /// </summary>
        public static string submenu_view {
            get {
                return ResourceManager.GetString("submenu_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string tab_about {
            get {
                return ResourceManager.GetString("tab_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string tabs_about {
            get {
                return ResourceManager.GetString("tabs_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string tabs_admin {
            get {
                return ResourceManager.GetString("tabs_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string tabs_community {
            get {
                return ResourceManager.GetString("tabs_community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string tabs_contact {
            get {
                return ResourceManager.GetString("tabs_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string tabs_courses {
            get {
                return ResourceManager.GetString("tabs_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string tabs_help {
            get {
                return ResourceManager.GetString("tabs_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string tabs_home {
            get {
                return ResourceManager.GetString("tabs_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string tabs_login {
            get {
                return ResourceManager.GetString("tabs_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string tabs_logout {
            get {
                return ResourceManager.GetString("tabs_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string tabs_profile {
            get {
                return ResourceManager.GetString("tabs_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour.
        /// </summary>
        public static string tabs_tour {
            get {
                return ResourceManager.GetString("tabs_tour", resourceCulture);
            }
        }
    }
}
