//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Didache.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Didache.Resources.labels", typeof(labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string changepassword_confirmnewpassword {
            get {
                return ResourceManager.GetString("changepassword_confirmnewpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string changepassword_currentpassword {
            get {
                return ResourceManager.GetString("changepassword_currentpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string changepassword_fail {
            get {
                return ResourceManager.GetString("changepassword_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string changepassword_newpassword {
            get {
                return ResourceManager.GetString("changepassword_newpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match.
        /// </summary>
        public static string changepassword_nomatch {
            get {
                return ResourceManager.GetString("changepassword_nomatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password was successfully changed.
        /// </summary>
        public static string changepassword_success {
            get {
                return ResourceManager.GetString("changepassword_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alumni.
        /// </summary>
        public static string commonmenu_alumni {
            get {
                return ResourceManager.GetString("commonmenu_alumni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Center.
        /// </summary>
        public static string commonmenu_bookcenter {
            get {
                return ResourceManager.GetString("commonmenu_bookcenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CampusNet.
        /// </summary>
        public static string commonmenu_campusnet {
            get {
                return ResourceManager.GetString("commonmenu_campusnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTS Website.
        /// </summary>
        public static string commonmenu_dtswebsite {
            get {
                return ResourceManager.GetString("commonmenu_dtswebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string commonmenu_library {
            get {
                return ResourceManager.GetString("commonmenu_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Ed.
        /// </summary>
        public static string commonmenu_onlineed {
            get {
                return ResourceManager.GetString("commonmenu_onlineed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Classmate.
        /// </summary>
        public static string community_addclassmate_button {
            get {
                return ResourceManager.GetString("community_addclassmate_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Request.
        /// </summary>
        public static string community_approveclassmate_button {
            get {
                return ResourceManager.GetString("community_approveclassmate_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Think &apos;friends&apos; on Facebook, but without any of the theological connotations seminary students think of when they see &apos;friend&apos; or &apos;follower.&apos;.
        /// </summary>
        public static string community_classmates_desc {
            get {
                return ResourceManager.GetString("community_classmates_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classmate.
        /// </summary>
        public static string community_relationshipstatus_classmate {
            get {
                return ResourceManager.GetString("community_relationshipstatus_classmate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string community_relationshipstatus_pending {
            get {
                return ResourceManager.GetString("community_relationshipstatus_pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string community_search_button {
            get {
                return ResourceManager.GetString("community_search_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for friends like Darrell Bock.
        /// </summary>
        public static string community_search_placeholder {
            get {
                return ResourceManager.GetString("community_search_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string community_search_title {
            get {
                return ResourceManager.GetString("community_search_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Classmates.
        /// </summary>
        public static string community_searchbycourse_button {
            get {
                return ResourceManager.GetString("community_searchbycourse_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        public static string confirm_delete {
            get {
                return ResourceManager.GetString("confirm_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Courses.
        /// </summary>
        public static string coursemenu_active_courses {
            get {
                return ResourceManager.GetString("coursemenu_active_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived Courses.
        /// </summary>
        public static string coursemenu_archived_courses {
            get {
                return ResourceManager.GetString("coursemenu_archived_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string coursemenu_calendar {
            get {
                return ResourceManager.GetString("coursemenu_calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string coursemenu_other_courses {
            get {
                return ResourceManager.GetString("coursemenu_other_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived Courses.
        /// </summary>
        public static string courses_heading_archivedcourses {
            get {
                return ResourceManager.GetString("courses_heading_archivedcourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments.
        /// </summary>
        public static string courses_heading_assignments {
            get {
                return ResourceManager.GetString("courses_heading_assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Description.
        /// </summary>
        public static string courses_heading_coursedesc {
            get {
                return ResourceManager.GetString("courses_heading_coursedesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Files.
        /// </summary>
        public static string courses_heading_coursefiles {
            get {
                return ResourceManager.GetString("courses_heading_coursefiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Roster.
        /// </summary>
        public static string courses_heading_courseroster {
            get {
                return ResourceManager.GetString("courses_heading_courseroster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming....
        /// </summary>
        public static string courses_heading_dashboard {
            get {
                return ResourceManager.GetString("courses_heading_dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string courses_heading_tools {
            get {
                return ResourceManager.GetString("courses_heading_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string courses_heading_units {
            get {
                return ResourceManager.GetString("courses_heading_units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graded Files.
        /// </summary>
        public static string courses_label_gradedfiles {
            get {
                return ResourceManager.GetString("courses_label_gradedfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Feed.
        /// </summary>
        public static string courses_tools_icalendar {
            get {
                return ResourceManager.GetString("courses_tools_icalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the links below to import course requirements into your calendar program (Mac Mail, Outlook, Google Calendar, etc.).
        /// </summary>
        public static string courses_tools_icalendar_desc {
            get {
                return ResourceManager.GetString("courses_tools_icalendar_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTunes Feed.
        /// </summary>
        public static string courses_tools_itunes {
            get {
                return ResourceManager.GetString("courses_tools_itunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import course videos, slides, and transcripts into iTunes (or other media software) for offline viewing. In iTunes, copy this URL, click on &quot;Advanced&quot; in the menu, select &quot;Subscribe to Podcast,&quot; and then paste the URL..
        /// </summary>
        public static string courses_tools_itunes_desc {
            get {
                return ResourceManager.GetString("courses_tools_itunes_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments.
        /// </summary>
        public static string coursetabs_assignments {
            get {
                return ResourceManager.GetString("coursetabs_assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get your graded stuff.
        /// </summary>
        public static string coursetabs_assignments_desc {
            get {
                return ResourceManager.GetString("coursetabs_assignments_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string coursetabs_dashboard {
            get {
                return ResourceManager.GetString("coursetabs_dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All your base.
        /// </summary>
        public static string coursetabs_dashboard_desc {
            get {
                return ResourceManager.GetString("coursetabs_dashboard_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the important information about your class.
        /// </summary>
        public static string coursetabs_dashboard_desc_long {
            get {
                return ResourceManager.GetString("coursetabs_dashboard_desc_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discussion.
        /// </summary>
        public static string coursetabs_discussion {
            get {
                return ResourceManager.GetString("coursetabs_discussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Forums.
        /// </summary>
        public static string coursetabs_discussion_desc {
            get {
                return ResourceManager.GetString("coursetabs_discussion_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string coursetabs_files {
            get {
                return ResourceManager.GetString("coursetabs_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prof&apos;s materials.
        /// </summary>
        public static string coursetabs_files_desc {
            get {
                return ResourceManager.GetString("coursetabs_files_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roster.
        /// </summary>
        public static string coursetabs_roster {
            get {
                return ResourceManager.GetString("coursetabs_roster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet your classmates.
        /// </summary>
        public static string coursetabs_roster_desc {
            get {
                return ResourceManager.GetString("coursetabs_roster_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string coursetabs_schedule {
            get {
                return ResourceManager.GetString("coursetabs_schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dates &amp;amp; assignments.
        /// </summary>
        public static string coursetabs_schedule_desc {
            get {
                return ResourceManager.GetString("coursetabs_schedule_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string coursetabs_tools {
            get {
                return ResourceManager.GetString("coursetabs_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads, Calendars, and RSS feeds.
        /// </summary>
        public static string coursetabs_tools_desc {
            get {
                return ResourceManager.GetString("coursetabs_tools_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while processing your request.
        /// </summary>
        public static string error_desc {
            get {
                return ResourceManager.GetString("error_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string forums_by {
            get {
                return ResourceManager.GetString("forums_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Forums.
        /// </summary>
        public static string forums_courseforums {
            get {
                return ResourceManager.GetString("forums_courseforums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum Name.
        /// </summary>
        public static string forums_header_forumname {
            get {
                return ResourceManager.GetString("forums_header_forumname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Post.
        /// </summary>
        public static string forums_header_lastpost {
            get {
                return ResourceManager.GetString("forums_header_lastpost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string forums_header_threadsubject {
            get {
                return ResourceManager.GetString("forums_header_threadsubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string forums_header_totalposts {
            get {
                return ResourceManager.GetString("forums_header_totalposts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replies.
        /// </summary>
        public static string forums_header_totalreplies {
            get {
                return ResourceManager.GetString("forums_header_totalreplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threads.
        /// </summary>
        public static string forums_header_totalthreads {
            get {
                return ResourceManager.GetString("forums_header_totalthreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string forums_header_totalviews {
            get {
                return ResourceManager.GetString("forums_header_totalviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string forums_replytopost {
            get {
                return ResourceManager.GetString("forums_replytopost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string group_editor_description {
            get {
                return ResourceManager.GetString("group_editor_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Settings.
        /// </summary>
        public static string group_editor_header {
            get {
                return ResourceManager.GetString("group_editor_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string group_editor_image {
            get {
                return ResourceManager.GetString("group_editor_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string group_editor_name {
            get {
                return ResourceManager.GetString("group_editor_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string group_editor_type {
            get {
                return ResourceManager.GetString("group_editor_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Group.
        /// </summary>
        public static string group_save_button {
            get {
                return ResourceManager.GetString("group_save_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string groups_list {
            get {
                return ResourceManager.GetString("groups_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create or join groups to discuss ministry with DTS alumni and students..
        /// </summary>
        public static string groups_list_description {
            get {
                return ResourceManager.GetString("groups_list_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email.
        /// </summary>
        public static string help_email {
            get {
                return ResourceManager.GetString("help_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;re having a login problem, please use the &lt;a href=&quot;http://www.dts.edu/account/resetpassword&quot;&gt;reset password&lt;/a&gt; link to reset your password. If you have a question about an assignment, please contact your professor or facilitator..
        /// </summary>
        public static string help_instructions {
            get {
                return ResourceManager.GetString("help_instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of Problem.
        /// </summary>
        public static string help_message {
            get {
                return ResourceManager.GetString("help_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string help_name {
            get {
                return ResourceManager.GetString("help_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Problem.
        /// </summary>
        public static string help_submit {
            get {
                return ResourceManager.GetString("help_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your feedback. Someone will respond as soon as possible..
        /// </summary>
        public static string help_submitted {
            get {
                return ResourceManager.GetString("help_submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help/Contact.
        /// </summary>
        public static string help_title {
            get {
                return ResourceManager.GetString("help_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Courses.
        /// </summary>
        public static string home_currentcourses {
            get {
                return ResourceManager.GetString("home_currentcourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bibliography Software.
        /// </summary>
        public static string home_dashboard_heading_bibsoftware {
            get {
                return ResourceManager.GetString("home_dashboard_heading_bibsoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Resources.
        /// </summary>
        public static string home_dashboard_heading_courseresources {
            get {
                return ResourceManager.GetString("home_dashboard_heading_courseresources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Education Resources.
        /// </summary>
        public static string home_dashboard_heading_onlineedresources {
            get {
                return ResourceManager.GetString("home_dashboard_heading_onlineedresources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s Happening on MyDTS.
        /// </summary>
        public static string home_dashboard_heading_stream {
            get {
                return ResourceManager.GetString("home_dashboard_heading_stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming.
        /// </summary>
        public static string home_dashboard_heading_upcoming {
            get {
                return ResourceManager.GetString("home_dashboard_heading_upcoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download all files (current courses).
        /// </summary>
        public static string home_dashboard_li_downloadallfiles {
            get {
                return ResourceManager.GetString("home_dashboard_li_downloadallfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download your term calendar.
        /// </summary>
        public static string home_dashboard_li_downloadcalendar {
            get {
                return ResourceManager.GetString("home_dashboard_li_downloadcalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndNote.
        /// </summary>
        public static string home_dashboard_li_endnote {
            get {
                return ResourceManager.GetString("home_dashboard_li_endnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LibreOffice.org.
        /// </summary>
        public static string home_dashboard_li_libreoffice {
            get {
                return ResourceManager.GetString("home_dashboard_li_libreoffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Word Compatibility Pack.
        /// </summary>
        public static string home_dashboard_li_msword {
            get {
                return ResourceManager.GetString("home_dashboard_li_msword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleEase.
        /// </summary>
        public static string home_dashboard_li_styleease {
            get {
                return ResourceManager.GetString("home_dashboard_li_styleease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turabian Format Tutorial.
        /// </summary>
        public static string home_dashboard_li_turabianformattutorial {
            get {
                return ResourceManager.GetString("home_dashboard_li_turabianformattutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zotero (free).
        /// </summary>
        public static string home_dashboard_li_zotero {
            get {
                return ResourceManager.GetString("home_dashboard_li_zotero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not registered to take any current classes..
        /// </summary>
        public static string home_nocourses {
            get {
                return ResourceManager.GetString("home_nocourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the home page where all your stuff should be.
        /// </summary>
        public static string homemenu_message {
            get {
                return ResourceManager.GetString("homemenu_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Page.
        /// </summary>
        public static string index_title {
            get {
                return ResourceManager.GetString("index_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open [{0} Replies].
        /// </summary>
        public static string interactions_replies {
            get {
                return ResourceManager.GetString("interactions_replies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string labels_dashboard_downloadallfiles {
            get {
                return ResourceManager.GetString("labels_dashboard_downloadallfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faciliators.
        /// </summary>
        public static string labels_dashboard_facilitators {
            get {
                return ResourceManager.GetString("labels_dashboard_facilitators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty.
        /// </summary>
        public static string labels_dashboard_faculty {
            get {
                return ResourceManager.GetString("labels_dashboard_faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Members.
        /// </summary>
        public static string labels_dashboard_groupmembers {
            get {
                return ResourceManager.GetString("labels_dashboard_groupmembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Assignments.
        /// </summary>
        public static string labels_dashboard_keyassignments {
            get {
                return ResourceManager.GetString("labels_dashboard_keyassignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string labels_dashboard_keydownloads {
            get {
                return ResourceManager.GetString("labels_dashboard_keydownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syllabus.
        /// </summary>
        public static string labels_dashboard_syllabus {
            get {
                return ResourceManager.GetString("labels_dashboard_syllabus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot ID/Password.
        /// </summary>
        public static string login_forgotpassword {
            get {
                return ResourceManager.GetString("login_forgotpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username and password.
        /// </summary>
        public static string login_instructions {
            get {
                return ResourceManager.GetString("login_instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string login_legend {
            get {
                return ResourceManager.GetString("login_legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login_login {
            get {
                return ResourceManager.GetString("login_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string login_logout {
            get {
                return ResourceManager.GetString("login_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string login_password {
            get {
                return ResourceManager.GetString("login_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your DTS ID is the same here and on CampusNet, but your password may be different. Your default password is your DTS ID and the first initial of your last name (John Doe = 123456d)..
        /// </summary>
        public static string login_passwordmessage {
            get {
                return ResourceManager.GetString("login_passwordmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep me logged in.
        /// </summary>
        public static string login_rememberme {
            get {
                return ResourceManager.GetString("login_rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login_title {
            get {
                return ResourceManager.GetString("login_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string login_unsuccessful {
            get {
                return ResourceManager.GetString("login_unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTS ID.
        /// </summary>
        public static string login_username {
            get {
                return ResourceManager.GetString("login_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string profile_changepassword {
            get {
                return ResourceManager.GetString("profile_changepassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alumni.
        /// </summary>
        public static string profile_constituency_alumni {
            get {
                return ResourceManager.GetString("profile_constituency_alumni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty.
        /// </summary>
        public static string profile_constituency_faculty {
            get {
                return ResourceManager.GetString("profile_constituency_faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string profile_constituency_staff {
            get {
                return ResourceManager.GetString("profile_constituency_staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string profile_constituency_student {
            get {
                return ResourceManager.GetString("profile_constituency_student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string profile_edit_button {
            get {
                return ResourceManager.GetString("profile_edit_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string profile_heading_contactinfo {
            get {
                return ResourceManager.GetString("profile_heading_contactinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Photo.
        /// </summary>
        public static string profile_heading_existingphoto {
            get {
                return ResourceManager.GetString("profile_heading_existingphoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string profile_heading_notifications {
            get {
                return ResourceManager.GetString("profile_heading_notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string profile_heading_personalinfo {
            get {
                return ResourceManager.GetString("profile_heading_personalinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string profile_heading_preferences {
            get {
                return ResourceManager.GetString("profile_heading_preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Security Settings.
        /// </summary>
        public static string profile_heading_security {
            get {
                return ResourceManager.GetString("profile_heading_security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media.
        /// </summary>
        public static string profile_heading_socialmedia {
            get {
                return ResourceManager.GetString("profile_heading_socialmedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload New Photo.
        /// </summary>
        public static string profile_heading_uploadnewphoto {
            get {
                return ResourceManager.GetString("profile_heading_uploadnewphoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload a photo that [1] shows only you (we love families, but it&apos;s harder to interact with them!), [2] is cropped to show mostly your face and shoulders (the rest of you is great, we just want to see your face!).
        /// </summary>
        public static string profile_heading_uploadnewphoto_desc {
            get {
                return ResourceManager.GetString("profile_heading_uploadnewphoto_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string profile_label_address {
            get {
                return ResourceManager.GetString("profile_label_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biography.
        /// </summary>
        public static string profile_label_biography {
            get {
                return ResourceManager.GetString("profile_label_biography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        public static string profile_label_birthday {
            get {
                return ResourceManager.GetString("profile_label_birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Photo.
        /// </summary>
        public static string profile_label_changephoto {
            get {
                return ResourceManager.GetString("profile_label_changephoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        public static string profile_label_children {
            get {
                return ResourceManager.GetString("profile_label_children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classmate Requests.
        /// </summary>
        public static string profile_label_classmaterequests {
            get {
                return ResourceManager.GetString("profile_label_classmaterequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Classmates.
        /// </summary>
        public static string profile_label_commonclassmates {
            get {
                return ResourceManager.GetString("profile_label_commonclassmates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You and {0} do not have any common classmates..
        /// </summary>
        public static string profile_label_commonclassmates_none {
            get {
                return ResourceManager.GetString("profile_label_commonclassmates_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses You Took Together.
        /// </summary>
        public static string profile_label_commoncourses {
            get {
                return ResourceManager.GetString("profile_label_commoncourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You and {0} did not take any courses together..
        /// </summary>
        public static string profile_label_commoncourses_none {
            get {
                return ResourceManager.GetString("profile_label_commoncourses_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Schedule.
        /// </summary>
        public static string profile_label_coursessecurity {
            get {
                return ResourceManager.GetString("profile_label_coursessecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This controls whether or not other students can see if you took a course together..
        /// </summary>
        public static string profile_label_coursessecurity_description {
            get {
                return ResourceManager.GetString("profile_label_coursessecurity_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string profile_label_email {
            get {
                return ResourceManager.GetString("profile_label_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hometown.
        /// </summary>
        public static string profile_label_hometown {
            get {
                return ResourceManager.GetString("profile_label_hometown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string profile_label_language {
            get {
                return ResourceManager.GetString("profile_label_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string profile_label_phone {
            get {
                return ResourceManager.GetString("profile_label_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Picture.
        /// </summary>
        public static string profile_label_picturesecurity {
            get {
                return ResourceManager.GetString("profile_label_picturesecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls who can see your picture.
        /// </summary>
        public static string profile_label_picturesecurity_description {
            get {
                return ResourceManager.GetString("profile_label_picturesecurity_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spouse.
        /// </summary>
        public static string profile_label_spouse {
            get {
                return ResourceManager.GetString("profile_label_spouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone.
        /// </summary>
        public static string profile_label_timezone {
            get {
                return ResourceManager.GetString("profile_label_timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string profile_label_work {
            get {
                return ResourceManager.GetString("profile_label_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Profile.
        /// </summary>
        public static string profile_save_button {
            get {
                return ResourceManager.GetString("profile_save_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All DTS.
        /// </summary>
        public static string profile_security_all {
            get {
                return ResourceManager.GetString("profile_security_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classmates.
        /// </summary>
        public static string profile_security_friends {
            get {
                return ResourceManager.GetString("profile_security_friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string profile_security_private {
            get {
                return ResourceManager.GetString("profile_security_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Photo.
        /// </summary>
        public static string profile_uploadphotobutton {
            get {
                return ResourceManager.GetString("profile_uploadphotobutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string studentschedule_choose {
            get {
                return ResourceManager.GetString("studentschedule_choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please submit one of the following file types:.
        /// </summary>
        public static string studentschedule_chooseafiletype {
            get {
                return ResourceManager.GetString("studentschedule_chooseafiletype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string studentschedule_file {
            get {
                return ResourceManager.GetString("studentschedule_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The instructions for this assignment will be available {0}..
        /// </summary>
        public static string studentschedule_instructionsnotavailable {
            get {
                return ResourceManager.GetString("studentschedule_instructionsnotavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Completed.
        /// </summary>
        public static string studentschedule_markcompleted {
            get {
                return ResourceManager.GetString("studentschedule_markcompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no discussions ready for you to comment upon. Check back soon..
        /// </summary>
        public static string studentschedule_nopostsyet {
            get {
                return ResourceManager.GetString("studentschedule_nopostsyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record % Complete.
        /// </summary>
        public static string studentschedule_recordpercentcomplete {
            get {
                return ResourceManager.GetString("studentschedule_recordpercentcomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you need to resubmit your file, please contact your facilitator..
        /// </summary>
        public static string studentschedule_resubmitfile_contactfacilitator {
            get {
                return ResourceManager.GetString("studentschedule_resubmitfile_contactfacilitator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already submitted this assignment. But since it is before the due date and no one has responded to your post, you can resubmit it replacing your earlier file..
        /// </summary>
        public static string studentschedule_resubmitfile_message {
            get {
                return ResourceManager.GetString("studentschedule_resubmitfile_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to Facilitator.
        /// </summary>
        public static string studentschedule_sendtofacilitator {
            get {
                return ResourceManager.GetString("studentschedule_sendtofacilitator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string studentschedule_skip {
            get {
                return ResourceManager.GetString("studentschedule_skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be able to submit this assignment begining {0}..
        /// </summary>
        public static string studentschedule_submissionnotavailable {
            get {
                return ResourceManager.GetString("studentschedule_submissionnotavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn in File.
        /// </summary>
        public static string studentschedule_submitfile {
            get {
                return ResourceManager.GetString("studentschedule_submitfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Assignment for Discussion.
        /// </summary>
        public static string studentschedule_submitfordiscussion {
            get {
                return ResourceManager.GetString("studentschedule_submitfordiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This unit is not yet available to view. It will come online soon..
        /// </summary>
        public static string studentschedule_unitnotactive {
            get {
                return ResourceManager.GetString("studentschedule_unitnotactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string submenu_archive {
            get {
                return ResourceManager.GetString("submenu_archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campuses.
        /// </summary>
        public static string submenu_campuses {
            get {
                return ResourceManager.GetString("submenu_campuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classmates.
        /// </summary>
        public static string submenu_community_classmates {
            get {
                return ResourceManager.GetString("submenu_community_classmates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string submenu_community_friends {
            get {
                return ResourceManager.GetString("submenu_community_friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string submenu_community_groups {
            get {
                return ResourceManager.GetString("submenu_community_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classmates.
        /// </summary>
        public static string submenu_community_home {
            get {
                return ResourceManager.GetString("submenu_community_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string submenu_community_search {
            get {
                return ResourceManager.GetString("submenu_community_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string submenu_courses {
            get {
                return ResourceManager.GetString("submenu_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string submenu_current {
            get {
                return ResourceManager.GetString("submenu_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string submenu_dashboard {
            get {
                return ResourceManager.GetString("submenu_dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string submenu_edit {
            get {
                return ResourceManager.GetString("submenu_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string submenu_files {
            get {
                return ResourceManager.GetString("submenu_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        public static string submenu_sessions {
            get {
                return ResourceManager.GetString("submenu_sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string submenu_tools {
            get {
                return ResourceManager.GetString("submenu_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string submenu_users {
            get {
                return ResourceManager.GetString("submenu_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile Page.
        /// </summary>
        public static string submenu_view {
            get {
                return ResourceManager.GetString("submenu_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter any suggestions or comments you may have for any component within this course thus far that might better help us assist you in this online learning initiative. REMEMBER: If you have any content related questions regarding the course, please contact your GTA. If you experience any technical difficulties that you need assistance with, please email us at coursemanagement@dts.edu..
        /// </summary>
        public static string survey_footer {
            get {
                return ResourceManager.GetString("survey_footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Interaction.
        /// </summary>
        public static string survey_header_classinteraction {
            get {
                return ResourceManager.GetString("survey_header_classinteraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Comments.
        /// </summary>
        public static string survey_header_comments {
            get {
                return ResourceManager.GetString("survey_header_comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter any suggestions, compliments, or complaints you have for any part of this course or the online education website..
        /// </summary>
        public static string survey_header_comments_desc {
            get {
                return ResourceManager.GetString("survey_header_comments_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devotional.
        /// </summary>
        public static string survey_header_devotional {
            get {
                return ResourceManager.GetString("survey_header_devotional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After completing the tasks in this unit, please complete this survey, commenting on the class components as they contributed to your learning thus far in this course. Your input is extremely valuable to the further development of this course and DTS&apos;s online learning initiative. Please rank each area from 1-5, 1 being the lowest, 5 the highest..
        /// </summary>
        public static string survey_header_instructions {
            get {
                return ResourceManager.GetString("survey_header_instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning Activity.
        /// </summary>
        public static string survey_header_learningactivity {
            get {
                return ResourceManager.GetString("survey_header_learningactivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation &amp; Layout.
        /// </summary>
        public static string survey_header_navigation {
            get {
                return ResourceManager.GetString("survey_header_navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading.
        /// </summary>
        public static string survey_header_reading {
            get {
                return ResourceManager.GetString("survey_header_reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &amp; Support.
        /// </summary>
        public static string survey_header_service {
            get {
                return ResourceManager.GetString("survey_header_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments.
        /// </summary>
        public static string survey_header_tasks {
            get {
                return ResourceManager.GetString("survey_header_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Presentation.
        /// </summary>
        public static string survey_header_video {
            get {
                return ResourceManager.GetString("survey_header_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Interface.
        /// </summary>
        public static string survey_header_website {
            get {
                return ResourceManager.GetString("survey_header_website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string survey_notapplicable {
            get {
                return ResourceManager.GetString("survey_notapplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clarity of Instructions.
        /// </summary>
        public static string survey_question_clarity {
            get {
                return ResourceManager.GetString("survey_question_clarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ease of Use.
        /// </summary>
        public static string survey_question_easeofuse {
            get {
                return ResourceManager.GetString("survey_question_easeofuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructional support from TAs/Instructors.
        /// </summary>
        public static string survey_question_instructionalsupport {
            get {
                return ResourceManager.GetString("survey_question_instructionalsupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearly labeled pages.
        /// </summary>
        public static string survey_question_labels {
            get {
                return ResourceManager.GetString("survey_question_labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was it driven from and helpful for course objectives?.
        /// </summary>
        public static string survey_question_learningobjectives {
            get {
                return ResourceManager.GetString("survey_question_learningobjectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout look and feel.
        /// </summary>
        public static string survey_question_lookandfeel {
            get {
                return ResourceManager.GetString("survey_question_lookandfeel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality/Value.
        /// </summary>
        public static string survey_question_qualityvalue {
            get {
                return ResourceManager.GetString("survey_question_qualityvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality/Value of Slides.
        /// </summary>
        public static string survey_question_slidesqualityvalue {
            get {
                return ResourceManager.GetString("survey_question_slidesqualityvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Support.
        /// </summary>
        public static string survey_question_techsupport {
            get {
                return ResourceManager.GetString("survey_question_techsupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality/Value of Video.
        /// </summary>
        public static string survey_question_videoqualityvalue {
            get {
                return ResourceManager.GetString("survey_question_videoqualityvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Problems (5 for no problems).
        /// </summary>
        public static string survey_question_videotechnicalproblems {
            get {
                return ResourceManager.GetString("survey_question_videotechnicalproblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Were the transcripts useful to you?.
        /// </summary>
        public static string survey_question_videotranscript {
            get {
                return ResourceManager.GetString("survey_question_videotranscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Survey.
        /// </summary>
        public static string survey_submitsurvey {
            get {
                return ResourceManager.GetString("survey_submitsurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for submitting the survey..
        /// </summary>
        public static string survey_thankyou {
            get {
                return ResourceManager.GetString("survey_thankyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string tab_about {
            get {
                return ResourceManager.GetString("tab_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string tabs_about {
            get {
                return ResourceManager.GetString("tabs_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string tabs_admin {
            get {
                return ResourceManager.GetString("tabs_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string tabs_community {
            get {
                return ResourceManager.GetString("tabs_community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string tabs_contact {
            get {
                return ResourceManager.GetString("tabs_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string tabs_courses {
            get {
                return ResourceManager.GetString("tabs_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequent Questions.
        /// </summary>
        public static string tabs_faq {
            get {
                return ResourceManager.GetString("tabs_faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string tabs_help {
            get {
                return ResourceManager.GetString("tabs_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string tabs_home {
            get {
                return ResourceManager.GetString("tabs_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string tabs_login {
            get {
                return ResourceManager.GetString("tabs_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string tabs_logout {
            get {
                return ResourceManager.GetString("tabs_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string tabs_profile {
            get {
                return ResourceManager.GetString("tabs_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string tabs_resources {
            get {
                return ResourceManager.GetString("tabs_resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour.
        /// </summary>
        public static string tabs_tour {
            get {
                return ResourceManager.GetString("tabs_tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string usersposts_post_button {
            get {
                return ResourceManager.GetString("usersposts_post_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone in.
        /// </summary>
        public static string usersposts_post_everyonein {
            get {
                return ResourceManager.GetString("usersposts_post_everyonein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share something here....
        /// </summary>
        public static string usersposts_post_placeholder {
            get {
                return ResourceManager.GetString("usersposts_post_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible to.
        /// </summary>
        public static string usersposts_post_visibleto {
            get {
                return ResourceManager.GetString("usersposts_post_visibleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string videos_hours {
            get {
                return ResourceManager.GetString("videos_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string videos_minutes {
            get {
                return ResourceManager.GetString("videos_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print all slides.
        /// </summary>
        public static string videos_printallslides {
            get {
                return ResourceManager.GetString("videos_printallslides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print all transcripts.
        /// </summary>
        public static string videos_printalltranscripts {
            get {
                return ResourceManager.GetString("videos_printalltranscripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string videos_seconds {
            get {
                return ResourceManager.GetString("videos_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slides.
        /// </summary>
        public static string videos_slides {
            get {
                return ResourceManager.GetString("videos_slides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Time.
        /// </summary>
        public static string videos_totaltime {
            get {
                return ResourceManager.GetString("videos_totaltime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transcript.
        /// </summary>
        public static string videos_transcript {
            get {
                return ResourceManager.GetString("videos_transcript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to watch.
        /// </summary>
        public static string videos_watch {
            get {
                return ResourceManager.GetString("videos_watch", resourceCulture);
            }
        }
    }
}
