//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.labels", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        internal static string confirm_delete {
            get {
                return ResourceManager.GetString("confirm_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Courses.
        /// </summary>
        internal static string coursemenu_active_courses {
            get {
                return ResourceManager.GetString("coursemenu_active_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived Courses.
        /// </summary>
        internal static string coursemenu_archived_courses {
            get {
                return ResourceManager.GetString("coursemenu_archived_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string coursemenu_calendar {
            get {
                return ResourceManager.GetString("coursemenu_calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string coursemenu_other_courses {
            get {
                return ResourceManager.GetString("coursemenu_other_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments.
        /// </summary>
        internal static string coursetabs_assignments {
            get {
                return ResourceManager.GetString("coursetabs_assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get your graded stuff.
        /// </summary>
        internal static string coursetabs_assignments_desc {
            get {
                return ResourceManager.GetString("coursetabs_assignments_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string coursetabs_dashboard {
            get {
                return ResourceManager.GetString("coursetabs_dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All your base.
        /// </summary>
        internal static string coursetabs_dashboard_desc {
            get {
                return ResourceManager.GetString("coursetabs_dashboard_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the important information about your class.
        /// </summary>
        internal static string coursetabs_dashboard_desc_long {
            get {
                return ResourceManager.GetString("coursetabs_dashboard_desc_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discussion.
        /// </summary>
        internal static string coursetabs_discussion {
            get {
                return ResourceManager.GetString("coursetabs_discussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Forums.
        /// </summary>
        internal static string coursetabs_discussion_desc {
            get {
                return ResourceManager.GetString("coursetabs_discussion_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string coursetabs_files {
            get {
                return ResourceManager.GetString("coursetabs_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prof&apos;s materials.
        /// </summary>
        internal static string coursetabs_files_desc {
            get {
                return ResourceManager.GetString("coursetabs_files_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roster.
        /// </summary>
        internal static string coursetabs_roster {
            get {
                return ResourceManager.GetString("coursetabs_roster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet your classmates.
        /// </summary>
        internal static string coursetabs_roster_desc {
            get {
                return ResourceManager.GetString("coursetabs_roster_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        internal static string coursetabs_schedule {
            get {
                return ResourceManager.GetString("coursetabs_schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dates &amp;amp; assignments.
        /// </summary>
        internal static string coursetabs_schedule_desc {
            get {
                return ResourceManager.GetString("coursetabs_schedule_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        internal static string forums_by {
            get {
                return ResourceManager.GetString("forums_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Forums.
        /// </summary>
        internal static string forums_courseforums {
            get {
                return ResourceManager.GetString("forums_courseforums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum Name.
        /// </summary>
        internal static string forums_header_forumname {
            get {
                return ResourceManager.GetString("forums_header_forumname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Post.
        /// </summary>
        internal static string forums_header_lastpost {
            get {
                return ResourceManager.GetString("forums_header_lastpost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string forums_header_threadsubject {
            get {
                return ResourceManager.GetString("forums_header_threadsubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        internal static string forums_header_totalposts {
            get {
                return ResourceManager.GetString("forums_header_totalposts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replies.
        /// </summary>
        internal static string forums_header_totalreplies {
            get {
                return ResourceManager.GetString("forums_header_totalreplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threads.
        /// </summary>
        internal static string forums_header_totalthreads {
            get {
                return ResourceManager.GetString("forums_header_totalthreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        internal static string forums_header_totalviews {
            get {
                return ResourceManager.GetString("forums_header_totalviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        internal static string forums_replytopost {
            get {
                return ResourceManager.GetString("forums_replytopost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the home page where all your stuff should be.
        /// </summary>
        internal static string homemenu_message {
            get {
                return ResourceManager.GetString("homemenu_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username and password.
        /// </summary>
        internal static string login_instructions {
            get {
                return ResourceManager.GetString("login_instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        internal static string login_legend {
            get {
                return ResourceManager.GetString("login_legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login_login {
            get {
                return ResourceManager.GetString("login_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string login_password {
            get {
                return ResourceManager.GetString("login_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        internal static string login_rememberme {
            get {
                return ResourceManager.GetString("login_rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login_title {
            get {
                return ResourceManager.GetString("login_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string login_username {
            get {
                return ResourceManager.GetString("login_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string tabs_about {
            get {
                return ResourceManager.GetString("tabs_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string tabs_admin {
            get {
                return ResourceManager.GetString("tabs_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        internal static string tabs_community {
            get {
                return ResourceManager.GetString("tabs_community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string tabs_contact {
            get {
                return ResourceManager.GetString("tabs_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        internal static string tabs_courses {
            get {
                return ResourceManager.GetString("tabs_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string tabs_help {
            get {
                return ResourceManager.GetString("tabs_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string tabs_home {
            get {
                return ResourceManager.GetString("tabs_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string tabs_login {
            get {
                return ResourceManager.GetString("tabs_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string tabs_logout {
            get {
                return ResourceManager.GetString("tabs_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string tabs_profile {
            get {
                return ResourceManager.GetString("tabs_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour.
        /// </summary>
        internal static string tabs_tour {
            get {
                return ResourceManager.GetString("tabs_tour", resourceCulture);
            }
        }
    }
}
